# Generated by Django 5.0.4 on 2024-05-02 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_registerrequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('surname', models.TextField(verbose_name='Фамилия')),
                ('father_name', models.TextField(verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Незарегистрированный учитель',
                'verbose_name_plural': 'Незарегистрированные учителя',
            },
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='lessonstudentinfo',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.kid', verbose_name='Студент'),
        ),
        migrations.CreateModel(
            name='AbstractKid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('surname', models.TextField(verbose_name='Фамилия')),
                ('father_name', models.TextField(verbose_name='Отчество')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Незарегистрированный ученик',
                'verbose_name_plural': 'Незарегистрированные ученики',
            },
        ),
        migrations.AddField(
            model_name='lessonstudentinfo',
            name='abstract_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.abstractkid', verbose_name='Незарегистрированный ученик'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='abstract_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.abstractteacher', verbose_name='Незарегистрированный преподаватель'),
        ),
    ]
