# Generated by Django 5.0.4 on 2024-05-02 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_abstractteacher_alter_lesson_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='abstract_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.abstractteacher', verbose_name='Незарегистрированный преподаватель'),
        ),
    ]
