# Generated by Django 5.0.4 on 2024-05-02 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_lesson_abstract_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='lessonstudentinfo',
            name='abstract_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.abstractkid', verbose_name='Незарегистрированный ученик'),
        ),
        migrations.AlterField(
            model_name='lessonstudentinfo',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.kid', verbose_name='Студент'),
        ),
    ]
