# Generated by Django 5.0.4 on 2024-05-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_profileraiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='uploads/avatars/', verbose_name='Аватар'),
        ),
    ]
