# Generated by Django 5.0.4 on 2024-05-06 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePasswordRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_password', models.TextField(verbose_name='Новый пароль')),
                ('know_previous_password', models.BooleanField(verbose_name='Пользователю известен предыдущий пароль?')),
                ('other_info', models.TextField(blank=True, verbose_name='Другая информация предоставленная пользователем')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на изменение пароля',
                'verbose_name_plural': 'Запросы на изменение пароля',
            },
        ),
    ]
