# Generated by Django 5.0.4 on 2024-05-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_changepasswordrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractkid',
            name='father_name',
            field=models.TextField(blank=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='abstractteacher',
            name='father_name',
            field=models.TextField(blank=True, verbose_name='Отчество'),
        ),
    ]
