# Generated by Django 5.0.4 on 2024-05-08 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_abstractkid_father_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoursPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(verbose_name='Количество часов')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Количество часов на предмет и группу',
                'verbose_name_plural': 'Количества часов на предмет и группу',
            },
        ),
    ]
