# Generated by Django 5.0.4 on 2024-05-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_hoursplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_courses',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Количество курсов'),
        ),
        migrations.AlterField(
            model_name='group',
            name='year_of_study',
            field=models.IntegerField(verbose_name='Цифровой индекс группы'),
        ),
    ]
